export interface DocPage {
  id: string
  title: string
  category: string
  description: string
  sections: {
    title: string
    content: string
    code?: string
    codeLanguage?: string
  }[]
}

export const docsData: Record<string, DocPage> = {
  introduction: {
    id: 'introduction',
    title: 'Introduction',
    category: 'Getting Started',
    description: 'Vulcan is an open-source, production-grade AI Agent SDK written from scratch in TypeScript.',
    sections: [
      {
        title: 'Core Philosophy',
        content: 'Vulcan targets developers who want complete control over their agent loops. Rather than introducing a heavy, opinionated framework with high abstraction overhead, Vulcan provides direct primitives for managing prompt history, invoking custom tools, performing safe handoffs, executing retries/fallbacks, and evaluating guardrails.',
      },
      {
        title: 'Why Vulcan?',
        content: 'Unlike traditional agent frameworks that vendor-lock you into specific models, memory patterns, or runtimes, Vulcan is built around three core layers: the Agent Configuration (static parameters), the RunContext (dynamic single-run details), and Session Storage (long-term database state). It is framework-free, type-safe, and runs natively on Google Gemini, OpenAI, or Anthropic Claude.',
      },
    ],
  },
  quickstart: {
    id: 'quickstart',
    title: 'Quickstart',
    category: 'Getting Started',
    description: 'Build and execute your first autonomous math agent in under 5 minutes.',
    sections: [
      {
        title: '1. Create a Custom Tool',
        content: 'Tools in Vulcan are defined using Zod schemas for input validation. The runner validates model arguments before execution, shielding your application from incorrect formats.',
        code: `import { Vulcan, z } from 'vulcan-agentic-sdk'

const calculatorTool = Vulcan.createTool({
  name: 'calculator',
  description: 'Perform arithmetic operations.',
  inputSchema: z.object({
    operation: z.enum(['add', 'multiply']),
    a: z.number(),
    b: z.number()
  }),
  async execute({ operation, a, b }) {
    return operation === 'add' ? { result: a + b } : { result: a * b }
  }
})`,
        codeLanguage: 'typescript'
      },
      {
        title: '2. Define and Run the Agent',
        content: 'Instantiate the agent with instructions, bind the calculator tool, and invoke the agent loop. Vulcan handles the tool calling cycle automatically using the default Gemini 2.5 Flash model.',
        code: `const mathAgent = Vulcan.createAgent({
  name: 'math-helper',
  instructions: 'Use the calculator tool for math requests.',
  tools: [calculatorTool]
})

async function main() {
  const result = await Vulcan.run(mathAgent, 'What is 42 multiplied by 13?')
  console.log('Result:', result.output) // Output: 546
}`,
        codeLanguage: 'typescript'
      }
    ],
  },
  installation: {
    id: 'installation',
    title: 'Installation',
    category: 'Getting Started',
    description: 'How to install the Vulcan SDK and configure LLM provider dependencies.',
    sections: [
      {
        title: 'Install the Base SDK',
        content: 'Vulcan has a lightweight footprint with zero heavy dependencies. Install it using npm, yarn, or pnpm:',
        code: `npm install vulcan-agentic-sdk`,
        codeLanguage: 'bash'
      },
      {
        title: 'Choose a Provider SDK',
        content: 'Install the official client library for your preferred LLM provider. Vulcan uses lazy-loading, so it only imports the SDK you actively call:',
        code: `# For Google Gemini (Default)
npm install @google/generative-ai

# For OpenAI
npm install openai

# For Anthropic Claude
npm install @anthropic-ai/sdk`,
        codeLanguage: 'bash'
      },
      {
        title: 'Configure Environment Keys',
        content: 'Set your API keys as environment variables or load them from a `.env` file in your root workspace. Vulcan automatically loads `.env` files if found:',
        code: `GEMINI_API_KEY="AIzaSy..."
OPENAI_API_KEY="sk-proj-..."
ANTHROPIC_API_KEY="sk-ant-..."`,
        codeLanguage: 'env'
      }
    ],
  },
  tools: {
    id: 'tools',
    title: 'Tools System',
    category: 'Core Primitives',
    description: 'Extend agent capabilities with executable, type-safe custom actions.',
    sections: [
      {
        title: 'Zod Validation & Execution Flow',
        content: 'Every Tool uses Zod to validate arguments generated by the model. If a model generates invalid arguments, Vulcan catches the parsing error before calling the handler, triggering an auto-correction trace.',
        code: `const getStockPrice = Vulcan.createTool({
  name: 'get_stock_price',
  description: 'Retrieve current price of a stock ticker.',
  inputSchema: z.object({
    ticker: z.string().toUpperCase().length(4)
  }),
  async execute({ ticker }) {
    // API call logic...
    return { price: 180.25 }
  }
})`,
        codeLanguage: 'typescript'
      },
      {
        title: 'Tool Execution Timeouts & Error Handlers',
        content: 'You can configure custom execution timeouts (default: 30000ms) and inline error handlers to return fallback messages safely without crashing the agent loop.',
        code: `const fetchWebPage = Vulcan.createTool({
  name: 'fetch_page',
  description: 'Download raw HTML from a URL.',
  inputSchema: z.object({ url: z.string().url() }),
  timeoutMs: 5000, // Timeout after 5 seconds
  errorHandler(error, input) {
    return \`Failed to fetch \${input.url}: \${error.message}. Return manual warning.\`
  },
  async execute({ url }) {
    // Download content...
  }
})`,
        codeLanguage: 'typescript'
      }
    ],
  },
  handoffs: {
    id: 'handoffs',
    title: 'Agent Handoffs',
    category: 'Advanced Patterns',
    description: 'Coordinate multiple specialized agents in a triage/delegation network.',
    sections: [
      {
        title: 'How Handoffs Work',
        content: 'Handoffs allow one agent to delegate the conversation to another agent. When an agent calls `.withHandoff(targetAgent)`, Vulcan injects a special \`handoff_to_<agent_name>\` tool. If the model invokes this tool, the runner handles the context shift and transfers the full chat history.',
        code: `const billingAgent = Vulcan.createAgent({
  name: 'billing',
  instructions: 'Help customers with payments and invoices.'
})

const triageAgent = Vulcan.createAgent({
  name: 'triage',
  instructions: 'Route the request. Billing queries should go to the billing specialist.'
}).withHandoff(billingAgent)`,
        codeLanguage: 'typescript'
      },
      {
        title: 'Handoff Loop Blocker',
        content: 'To prevent agents from delegating back and forth indefinitely, Vulcan tracks visited agents during a single run. If an agent is visited twice, the runner intercepts the loop and throws a `HandoffLoopError`.',
        code: `// Triage -> Billing -> Triage (Loop!)
// Vulcan detects this circular dependency and exits safely.`,
        codeLanguage: 'typescript'
      }
    ],
  },
  guardrails: {
    id: 'guardrails',
    title: 'Guardrails & Safety',
    category: 'Core Primitives',
    description: 'Intercept and validate inputs, outputs, and tool calls.',
    sections: [
      {
        title: 'Built-in Guardrails',
        content: 'Vulcan provides 5 built-in guardrail adapters that execute at run borders:',
        code: `import {
  MaxLengthGuardrail,
  KeywordBlockGuardrail,
  PIIScrubberGuardrail,
  BlockedToolsGuardrail
} from 'vulcan-agentic-sdk'

const guardrailedAgent = Vulcan.createAgent({
  name: 'secure-helper',
  instructions: 'Customer helper.',
  guardrails: [
    new MaxLengthGuardrail(500, { type: 'input' }),
    new KeywordBlockGuardrail(['hack', 'exploit'], { type: 'input' }),
    new PIIScrubberGuardrail() // Scrubs emails/phones from outputs
  ]
})`,
        codeLanguage: 'typescript'
      },
      {
        title: 'Custom Logic Guardrails',
        content: 'You can write custom functions that evaluate runtime variables. For example, blocking requests outside business hours:',
        code: `import { FunctionGuardrail } from 'vulcan-agentic-sdk'

const businessHoursGuard = new FunctionGuardrail('business-hours', 'input', async (payload) => {
  const hours = new Date().getUTCHours()
  if (hours < 6 || hours > 22) {
    return { passed: false, reason: 'System offline outside 6am-10pm UTC' }
  }
  return { passed: true }
})`,
        codeLanguage: 'typescript'
      }
    ],
  },
  'memory-sessions': {
    id: 'memory-sessions',
    title: 'Memory & Sessions',
    category: 'Core Primitives',
    description: 'Manage chat context and multi-turn state across storage adapters.',
    sections: [
      {
        title: 'Session Separation',
        content: 'Vulcan decouples the agent configuration from the conversation session storage. This makes it trivial to scale state in server environments. Vulcan provides 3 out-of-the-box adapters.',
      },
      {
        title: 'In-Memory Storage (Default)',
        content: 'Fast, non-persistent cache. Includes configurable TTL (Time to Live) options to automatically evict stale conversation contexts and conserve server resources.',
        code: `import { InMemoryStorage } from 'vulcan-agentic-sdk'

const cache = new InMemoryStorage({
  ttlMs: 3600000, // 1 hour TTL
  maxSessions: 1000 // Evict oldest if exceeding limit
})`,
        codeLanguage: 'typescript'
      },
      {
        title: 'SQLite Database Storage',
        content: 'Persistent file-backed storage. Stores chat sessions inside a local database table. If `better-sqlite3` is not installed, it falls back to memory storage with a console warning.',
        code: `import { SQLiteStorage } from 'vulcan-agentic-sdk'

const db = new SQLiteStorage('./database/vulcan-sessions.db')`,
        codeLanguage: 'typescript'
      }
    ],
  },
  tracing: {
    id: 'tracing',
    title: 'Tracing & Observability',
    category: 'Advanced Patterns',
    description: 'Inspect execution steps, token usage, and durations.',
    sections: [
      {
        title: 'Vulcan Tracer',
        content: 'A lightweight tracing engine captures all LLM and tool actions per run. Traces are stored in memory and can be exported as clean JSON objects or pretty-printed text layout tables.',
        code: `import { globalTracer } from 'vulcan-agentic-sdk'

const result = await Vulcan.run(agent, 'Help me build a pipeline.')
const trace = globalTracer.getTrace(result.traceId)

console.log(globalTracer.export(trace, 'pretty'))`,
        codeLanguage: 'typescript'
      },
      {
        title: 'Pretty Export Output Structure',
        content: 'The exported trace provides detailed timings and token counts for each turn, making debug analysis extremely convenient:',
        code: `╔══════════════════════════════════════════
║ Vulcan Trace — Run ID: 7da6ede0-a062-444f-819c-6f77716f7568
║ Agent: math-agent | Session: 657192f0-ecb1-49ac-acd5-98945c5f4a48
║ Status: completed | Duration: 5432ms
║ Tokens: 720 (↑497 ↓109)
╠══════════════════════════════════════════
║ Model Calls (3):
║   [gemini-2.5-flash] 2480ms — tool_calls — 265 tokens
║   [gemini-2.5-flash] 1632ms — tool_calls — 191 tokens
║   [gemini-2.5-flash] 1314ms — stop — 264 tokens
║ Tool Calls (2):
║   [✓ OK] calculator — 1ms
║   [✓ OK] calculator — 0ms
╚══════════════════════════════════════════`,
        codeLanguage: 'text'
      }
    ],
  }
}
